### ISSUE TITLE
Filtering - RFC3841 example (TCP) live test fails intermittently

### ISSUE THREAD

**Issue by tomwatson1024** [Metaswitch/clearwater-live-test#128]
#### Symptoms
The specified live test fails intermittently with output as follows:
Filtering - RFC3841 example (TCP) - (2010000004, 2010000489) Failed
Endpoint threw exception:
 - Call was not forked to binding 1
   - /home/ubuntu/clearwater-live-test/lib/tests/contact-filtering.rb:194:in 'block (2 levels) in <top (required)>'

#### Release and environment 
Deployment created on Amazon EC2 using Chef with packages copied from the staging repo dated 19/8/16 11:56:52.

#### Steps to reproduce
Run Clearwater live tests against such a deployment a few times.

**Comment by graemerobertson** [comment]
@rkd-msw didn't you have a theory on this?

**Comment by graemerobertson** [comment]
As far as I can tell, this test never passes when run on it's own (sample size is currently 8, which is fairly significant when you consider that it fails at most 1/20 times when not run on it's own). I'm going to figure this out today.

**Comment by graemerobertson** [comment]
My comment above is almost certainly a red herring, and is actually caused by the fact I'm running the tests on a really quick box or something; specifically, the test seems to pass every time if I increase [this sleep](https://github.com/Metaswitch/clearwater-live-test/blob/907a716e8be897c14ddb6d562ac95d3bdb617fe1/lib/tests/contact-filtering.rb#L185), and that's probably just ***the fix*** (or at least an indication of the cause of the failures)
